[package]
name = "scorecard"
version = "1.0.0"
authors = []

[addresses]
scorecard="0x0043b5060654a0a34c63a0d4cd0e871a170c23cf6aef89dad50538e7f9346089"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-cli-v2.1.0"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
