[package]
name = "scorecard"
version = "1.0.0"
authors = []

[addresses]
scorecard="0x4fbc68c737b5ef6a6d73c5c7d13a673b3b0503ab4ed9442418b46bbcf57ee8cf"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-cli-v2.1.0"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
